# Generated by Django 4.0 on 2022-01-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
